Correção no cálculo de taxa de rendimento
rendafixa/rendafixa.github.io pull request #64
Opened 2023-05-14 05:55 UTC by CleberL

Corrigido o problema no cálculo da taxa de rendimento do CDB, agora o calculo é sempre baseado em dias.
Também implementei uma seleção para que seja possível usar o sistema em dias, meses ou anos.

![image](https://github.com/rendafixa/rendafixa.github.io/assets/28936627/db18d911-a3db-4f79-a7bf-5fd339c725b4)

closes #51

2023-05-15 07:35 UTC, marcelorodrigo requested changes

2023-05-15 07:35 UTC, marcelorodrigo commented on src/poupanca.js
> +  return Math.pow(index / 100 + 1, 1 / 30)
Aqui temos um ponto de atenção. Estamos retornando o indice de retorno da poupança proporcional baseado em dias, mas a poupança tem sua remuneração calculada integralmente somente quando o depósito faz aniversário (podemos assumir aqui mensalmente já que não usamos o calendário com data fixa para início de investimentos).

2023-05-17 15:00 UTC, CleberL commented on src/poupanca.js
> +  return Math.pow(index / 100 + 1, 1 / 30)
Você tem razão, de fato o rendimento da poupança é aplicado nas datas de aniversário da aplicação, você tem alguma sugestão do que fazer com a visualização da poupança quando a seleção do período estiver por dias?

2023-05-17 16:05 UTC, marcelorodrigo commented on src/poupanca.js
> +  return Math.pow(index / 100 + 1, 1 / 30)
Você pode alterar a função poupança para agora receber o número de dias desejado, algo similar ao exemplo abaixo:

```suggestion
function getIndexPoupanca(index, days) {
  const daysInMonth = 30;
  const roundedDays = days < daysInMonth ? 0 : Math.floor(days / daysInMonth) * daysInMonth;
  return Math.pow(index / 100 + 1, roundedDays / daysInMonth);
}

```
Considerando 30 dias em cada mês, retorna a taxa somente quando o divisor for inteiro para esse valor.
Testes unitários ficaram assim:

```suggestion
const getIndexPoupanca = require('./poupanca.js');

describe('getIndexPoupanca', () => {
  test('Retorna 0 para dias menores que 30', () => {
    expect(getIndexPoupanca(6.5, 15)).toBe(0);
  });

  test('Retorna o índice de rendimento elevado a 1 para 30 dias', () => {
    expect(getIndexPoupanca(6.5, 30)).toBe(Math.pow(1 + 6.5 / 100, 1));
  });

  test('Retorna o índice de rendimento elevado a 1 para dias entre 30 e 59', () => {
    expect(getIndexPoupanca(6.5, 59)).toBe(Math.pow(1 + 6.5 / 100, 1));
  });

  test('Retorna o índice de rendimento elevado a 2 para 60 dias', () => {
    expect(getIndexPoupanca(6.5, 60)).toBe(Math.pow(1 + 6.5 / 100, 2));
  });

  test('Retorna o índice de rendimento elevado a 3 para 90 dias', () => {
    expect(getIndexPoupanca(6.5, 90)).toBe(Math.pow(1 + 6.5 / 100, 3));
  });
});

```

Acredito que na chamada do componente será necessário fazer alguns ajustes também.
O exemplo te ajuda?

2023-08-19 21:26 UTC, CleberL commented on src/poupanca.js
> +  return Math.pow(index / 100 + 1, 1 / 30)
Sim, ajuda bastante!!

2023-09-05 15:58 UTC, merged